### ISSUE TITLE
QUERY: Troubleshooting set-up instructions

### ISSUE THREAD

**Issue by s2ceball** [cwcon/push#1]
I've forked and am trying to clone PUSH through the terminal -- for now, just trying to clean up 3 copy-editing errors I found (to practice). I'm following the lovely instructions on [http://push.cwcon.org/setup.html](http://push.cwcon.org/setup.html) but I've run into a cmd line error when I try to clone it, saying "permission denied (public key)". I know I need to look up this error and it's probably some key issue I need to fix on my end, but I also wanted to test the Issue thing. So, an fyi and a "help" if you have time.

**Comment by karlstolley** [comment]
Can you run `cat .git/config` from inside the push directory and post the contents here?

**Comment by s2ceball** [comment]
Done. Got: 

cat: .git/config: No such file or directory

**Comment by karlstolley** [comment]
Oh, duh. I misread your post.

What happens when you run `ssh git@github.com`?

**Comment by s2ceball** [comment]
Oh, realized I'm doing this on my desktop. Don't have Xcode and all the other goodies installed on it. Just my laptop. Dangit. That's prolly the problem. I don't think I have any of it installed right on my desktop. (Just ran above: still getting Public Key error). Need to start from scratch to prep this machine. Will do and will get back to you if it's still not working .Thanks!

**Comment by s2ceball** [comment]
FYI (will add this to the readme when I can...noting here so I remember...)

 If you're running an older Mac OS (I'm running Snow leopard), you can't open the Mac App Store to download the current versions unless you have Lion or Mountain Lion. Instead, follow the links from the App Store to the Xcode page, then follow the link to "More Developer Tools," where you will have to sign up to be an Apple Developer (free) to get access to previous versions of XCode. Verify your email, then download Xcode. 

This is all easy -- just following directions and clicking links... But it's a work-around others might not know to do.

**Comment by steveklabnik** [comment]
You don't actually need XCode to get `git`: http://code.google.com/p/git-osx-installer/downloads/list?can=3&q=&sort=-uploaded&colspec=Filename+Summary+Uploaded+Size+DownloadCount

**Comment by cscorley** [comment]
It sounds like your error is an ssh key problem. Be sure to add that machine's key to GitHub so it knows about it. Alternatively, you can use https to clone instead of ssh.

edit: this guide should help https://help.github.com/articles/error-permission-denied-publickey
