### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vipulnsward** [cwcon/push#3]
There is a broken link to footnote citations on the push home page.

**Comment by brocktopus** [comment]
Specifically, I /believe/ this is for cfp.md under 'Basic Article Guidelines' ... I'll submit a pull request with it fixed (in branch "page-revision")

**Comment by karlstolley** [comment]
Thank you, Vipul. It's been fixed as of 4051ce03275bd950ba7a41e2d4b1034c36bef060
